name: Update niv

on:
  schedule:
    # every day at 8am UTC
    - cron:  '0 8 * * mon,wed,fri'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo rm -rf /opt /usr/local || true &
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: bbigras-nix-config
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: cachix use nix-community; cachix use nix-matrix-yggdrasil; cachix use eigenvalue; cachix use srid; cachix use niv
    - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} nix run '((import (import ./nix/sources.nix).niv {}).niv)' -c niv update
    - run: nix run '((import (import ./nix/sources.nix).nixpkgs {}).nix-build-uncached)' -c nix-build-uncached
    - run: nix-shell --run "echo OK"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
